FROM prom/prometheus:latest

# Expose Prometheus web UI port
EXPOSE 9090

# Copy custom Prometheus config if needed
COPY ./prometheus.yml /etc/prometheus/prometheus.yml

# The default entrypoint runs Prometheus